
IF(NOT DEFINED CTEST_NOTES_FILES)
    SET(CTEST_NOTES_FILES )
ENDIF(NOT DEFINED CTEST_NOTES_FILES)

LIST(APPEND CTEST_NOTES_FILES "/repos/tomopy/benchmarking/shepp2d/sirt/run_tomopy.out")

IF(NOT "${CTEST_NOTES_FILES}" STREQUAL "")
    LIST(REMOVE_DUPLICATES CTEST_NOTES_FILES)
ENDIF(NOT "${CTEST_NOTES_FILES}" STREQUAL "")

